import { readFile, writeFile } from 'node:fs/promises';

// The public llms catalog is generated by the canonical server registry.
const source = 'https://railyai.com/llms.txt';
const response = await fetch(source, { signal: AbortSignal.timeout(15000) });
if (!response.ok) throw new Error(`Canonical catalog HTTP ${response.status}`);
const text = await response.text();
const section = text.split('<!-- MCP-TOOLS:START -->')[1]?.split('<!-- MCP-TOOLS:END -->')[0];
if (!section || !text.includes('<!-- MCP-TOOLS:END -->')) throw new Error('Missing canonical catalog markers');
const lines = section.trim().split('\n');
const tools = lines.map(line => {
  const match = /^- `([a-z][a-z0-9_]+)` — (.+)$/.exec(line);
  if (!match) throw new Error('Malformed canonical tool entry');
  const mutating = match[2].endsWith(' (state-changing).');
  return { name: match[1], summary: mutating ? match[2].replace(/ \(state-changing\)\.$/, '.') : match[2], mutating };
});
if (!Array.isArray(tools) || tools.length === 0 || tools.some(t =>
  !/^[a-z][a-z0-9_]+$/.test(t.name) || typeof t.summary !== 'string' ||
  typeof t.mutating !== 'boolean') || new Set(tools.map(t => t.name)).size !== tools.length) {
  throw new Error('Invalid canonical catalog');
}
const markdown = `# Raily MCP tools\n\nGenerated from the [canonical server catalog](${source}).\nRun \`npm run catalog:sync\` to refresh and \`npm run catalog:check\` before release.\n\n${tools.length} registered tools. Supported revisions: \`2025-06-18\`, \`2025-11-25\`,\n\`2026-07-28\`. Registration and discovery do not grant execution permission.\nEach call needs the required scopes; writes also follow the server's approval,\nidempotency and feature-availability rules.\n\n| Tool | Changes state | Purpose |\n| --- | --- | --- |\n` + tools.map(t => `| \`${t.name}\` | ${t.mutating ? 'Yes' : 'No'} | ${t.summary.replaceAll('|', '\\|').replaceAll('\n', ' ')} |`).join('\n') + '\n';
for (const [path, expected] of [['mcp-tools.json', JSON.stringify(tools, null, 2) + '\n'], ['TOOLS.md', markdown]]) {
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8') !== expected) throw new Error(`${path} is stale; run npm run catalog:sync`);
  } else await writeFile(path, expected);
}
console.log(`Canonical catalog: ${tools.length} tools; ${process.argv.includes('--check') ? 'parity passed' : 'synchronized'}`);
